// src/seeders/ingredientes.seed.ts
export const ingredientesSeed = [
  { name: 'Manzana' },
  { name: 'Banana' },
  { name: 'Pollo' },
  { name: 'Arroz' },
  { name: 'Leche' },
  { name: 'Huevo' },
  { name: 'Espinaca' },
  { name: 'Tomate' },
  { name: 'Papa' },
  { name: 'Zanahoria' },
  { name: 'Brócoli' },
  { name: 'Queso' },
  { name: 'Pan' },
  { name: 'Lentejas' },
  { name: 'Frijoles' },
  { name: 'Avena' },
  { name: 'Yogur' },
  { name: 'Pescado' },
  { name: 'Carne de res' },
  { name: 'Pasta' },
  { name: 'Aguacate' },
  { name: 'Naranja' },
  { name: 'Pera' },
  { name: 'Calabaza' },
  { name: 'Pepino' },
  { name: 'Cebolla' },
  { name: 'Garbanzo' },
  { name: 'Maíz' },
  { name: 'Polenta' },
  { name: 'Tofu' }
];
